### ISSUE TITLE
[Map Character Appearances] Design Suggestions

### ISSUE THREAD

**Issue by harp37** [lmparppei/BeatPlugins#2]
I know this wouldn't be too hard to change, but I'm pretty new to coding in Swift, so here are some suggestions. (I will try to change them myself, but in the meanwhile, here are some of my thoughts.)

- Allow users to choose whether to include characters appearing in ACTION or just based on DIALOGUE.
- Allow users to show ONLY the scenes where characters APPEAR IN ACTION but don't have DIALOGUE (to show where characters should probably be cut).
- Graph based on SCENE NUMBER rather than PAGE COUNT, or at least have this as a viewing option. Perhaps with separators for each scene change. This will be much more DETAILED than the page-count view.

**Comment by lmparppei** [comment]
Plugins are written using JavaScript and results are shown in HTML, so you don't need to know any Swift :-)

The graph actually does use scene numbers on the x axis right now, not page numbers. To make it possible to toggle between dialogue/action/etc. the final graph building probably needs to be done in the HTML panel. The scene/character data has to be injected there somehow, and the object would have to be built so that there is a distinction between dialogue/action appearances.

If you just want a plugin for your our purposes to see only dialogue appearances, remove the code which checks the actions. It should be clearly commented. The results would be much more reliable, too, as names in actions are just educated guesses.

**Comment by lmparppei** [comment]
I'm actually reopening this issue, because it's a good suggestion, just needs some work.

**Comment by harp37** [comment]
Yeah, I didn't realize that it was based on scene number as the script I used to test it with was about a scene every page. I don't know how I missed seeing "Scene" on the top of the window. I might need to get my eyes checked.
